[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "sqlite"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
